### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by asifzubair** [mitoNGS/MToolBox#1]
It would be great if some example data/output was uploaded here . This way users can check their installation by running MToolBox on the examples and see if it matches up with the expected output. 

Thanks!

**Comment by clody23** [comment]
@asifzubair . Thanks for your suggestion and sorry for the very late reply. 

We uploaded two simulated paired-end fastq datasets in the test folder of the MToolBox repo:
 https://github.com/mitoNGS/MToolBox/blob/master/test/simulation100X.R1.fastq
https://github.com/mitoNGS/MToolBox/blob/master/test/simulation100X.R2.fastq
 (please refer to http://www.ncbi.nlm.nih.gov/pubmed/25028726 for further info about the dataset simulation).

Two output files were also uploaded:
-VCF_file.vcf
-logassemble.txt 
generated by running MToolBox, using  rCRS as reference sequence, as in this example:

export PATH=/path/to/MToolBox/:$PATH
./run_mtoolbox.sh

Thanks for using MToolBox!
Hope this will help

Cheers,
Claudia

**Comment by asifzubair** [comment]
Thank you, Claudia. Indeed, this is a great help.
