### ISSUE TITLE
documentation note: build db instructions

### ISSUE THREAD

**Issue by asifzubair** [mitoNGS/MToolBox#10]
The file names provided [here](https://github.com/mitoNGS/MToolBox/blob/master/how_to_build_db.md) for the reference genomes is slightly incorrect. 

The references are, in fact, `*.gz` files and not `*.tar.gz` files on sourceforge. Therefore, the `wget` commands will not work as-is. Obviously, the follow up commands also need to be modified to reflect this.

**Comment by robertopreste** [comment]
Hello @asifzubair and thanks for the issue you highlighted. We will fix this asap.

**Comment by clody23** [comment]
The documentation has been fixed.
