### ISSUE TITLE
line 207: `in-out_folders': not a valid identifier

### ISSUE THREAD

**Issue by bobbieshaban** [mitoNGS/MToolBox#16]
Hi,

I am trying to run MToolbox and I am receiving the error "line 207: `in-out_folders': not a valid identifier"

I performed a standard installation and this is my config shell
[shabanb@thing1 mtoolsbox]$ cat config_me.sh
input_type=fastq
ref=CG5.target
output_name=/data/Bioinfo/bioinfo-proj-bobbie/newProgs/MtoolBox/CAGRF10964/mtoolsbox/test_out/

my file names are as such
CG5_ALE07.R1.fastq
CG5_ALE07.R2.fastq
CG5.target.fa

And below is the full command and output
`[shabanb@thing1 mtoolsbox]$ sh MToolBox.sh -i config.sh -m "-t 20" -a "-t 10 -z 0.6"

setting up MToolBox environment variables...
...done

setting up MToolBox variables in config file ...
...done

Check python version... (2.7 required)
OK.

Checking files to be used in MToolBox execution...

Checking mapExome parameters...
OK.

Checking assembleMTgenome parameters...
OK.

Checking mt-classifier parameters...
OK.
/data/Bioinfo/bioinfo-proj-bobbie/newProgs/MtoolBox/MToolBox/MToolBox.sh: line 207: `in-out_folders': not a valid identifier
`

**Comment by bobbieshaban** [comment]
Sorry, the command line is actually

sh MToolBox.sh -i config_me.sh -m "-t 20" -a "-t 10 -z 0.6"

which produces the same error.

Thanks for your help!

**Comment by domenico-simone** [comment]
Hi Bobby,

sorry for this huge delay in replying. Apparently there could be some issue in the name we adopted for the function, even if it's the first time we have a report like this. Which OS do you use?

Best regards,
Domenico

**Comment by domenico-simone** [comment]
I have changed the name of the function `in-out_folder` in `in_out_folder` which should be more compliant to a wider range of standards.

**Comment by bobbieshaban** [comment]
Thanks Domenico!

I will download again and give another test.

Bobbie.
