### ISSUE TITLE
mapExome.py in the wrong directory

### ISSUE THREAD

**Issue by eturro** [mitoNGS/MToolBox#21]
It seems that mapExome.py cd's into the wrong directory at some point:

```
##### EXECUTING READ MAPPING WITH MAPEXOME...


mapExome for sample U006279_A_MT, files found: test_out/U006279_A_MT.fastq test_out/U006279_A_MT.R1.fastq test_out/U006279_A_MT.R2.fastq
U006279_A_MT.fastq is an empty unpaired fastq. File has been removed.
Traceback (most recent call last):
  File "/scratch/et341/MT/MToolBox/MToolBox/MToolBox/mapExome.py", line 66, in <module>
    if not os.path.exists(folder): os.mkdir(folder)
OSError: [Errno 2] No such file or directory: 'test_out/OUT_U006279_A_MT'
```

I added os.chdir("..") before that line and the script then proceeds further. But then I get an error further down:

```
##### EXECUTING READ MAPPING WITH MAPEXOME...


mapExome for sample U006279_A_MT, files found: test_out/U006279_A_MT.fastq test_out/U006279_A_MT.R1.fastq test_out/U006279_A_MT.R2.fastq
U006279_A_MT.fastq is an empty unpaired fastq. File has been removed.
Mapping onto mtDNA...
/scratch/et341/MT/MToolBox/MToolBox/bin/gmap/bin/gsnap -D /scratch/et341/MT/MToolBox/MToolBox/gmapdb/ --gunzip -d chrRCRS -A sam --nofails --pairmax-dna=500 --query-unk-mismatch=1 --read-group-id=sample --read-group-name=sample --read-group-library=sample --read-group-platform=sample -n 1 -Q -O -t 8 U006279_A_MT.R1.fastq U006279_A_MT.R2.fastq > test_out/OUT_U006279_A_MT/outmt.sam 2> test_out/OUT_U006279_A_MT/logmt.txt
Extracting FASTQ from SAM...
Reading Results...
Filtering reads...
Outfile saved on test_out/OUT_U006279_A_MT/OUT.sam.
Done.

Compression of fastq files from bam/sam input files...
mkdir: cannot create directory `test_out/processed_fastq': No such file or directory
mv: target `test_out/processed_fastq' is not a directory
./MToolBox.sh: line 337: cd: test_out: No such file or directory
tar: processed_fastq: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
rm: cannot remove `processed_fastq': No such file or directory
Done.
```

Advice would be much appreciated.

**Comment by clody23** [comment]
Hi, 
can you please let me know which MToolBox version you are using?
If you are using MToolBox v1.0, can you please specify the **full path** to the U006279_A_MT file in the config file?

like this:
```
input_path=/path/to/inputfile/
list=U006279_A_MT
input_type=fastq
...
```
Please, let me know if the issue persists.

cheers,
Claudia

**Comment by eturro** [comment]
Hi
I cloned it just recently so yes, 1.0.

The input_type is bam so I have input_type=bam not fastq

list was is set to the path to a text file with the BAM file names (i.e., including U006279_A_MT.bam) but I can change it to U006279_A_MT, as you have instructed, which leads to the same problem -

Compression of fastq files from bam/sam input files...
mkdir: cannot create directory `test_out/processed_fastq': No such file or directory
mv: target `test_out/processed_fastq' is not a directory



thanks
Ernest

**Comment by clody23** [comment]
Hi Ernest,

yes, sorry I thought your input was fastq. Actually you should specify the full file name in the config file (as I think you are doing)
```
list=U006279_A_MT.bam
```
maybe it's a wrong guess, but it looks like the MToolBox.sh is not able find the output directory where to open the `processed_fastq` folder and move the fastq files.

The line of codes in the MToolBox.sh that seem to fail are these ones (335-337):
```
mkdir ${output_name}/processed_fastq
for i in $sampleIDs; do mv $i*fastq ${output_name}/processed_fastq; done
cd ${output_name}	
```
So I think MToolBox.sh is having problem locating the `$output_name`  directory...

Based on the log you pasted `test_out` is the working directory where you placed your input bam file and when you also want to output results. However, from the log it seems you are not specifying the absolute path names of the input/output dir: 
```
mapExome for sample U006279_A_MT, files found: test_out/U006279_A_MT.fastq test_out/U006279_A_MT.R1.fastq test_out/U006279_A_MT.R2.fastq
```
and
```
Outfile saved on test_out/OUT_U006279_A_MT/OUT.sam.
```
(where test_out/... looks like relative path)

I would suggest to try specifying the full path name of the **input and output directory** in the config file. 

E.g.:
```
input_path=input_path=/path/name/to/test_out/
output_name=/path/name/to/test_out/
list=U006279_A_MT.bam
```

and try again to run MToolBox. Also, if you don't mind, can you please paste me the config file you are using and the full MToolBox log? That would maybe help.

Hope this helps. 
cheers,
C

**Comment by eturro** [comment]
Hi Claudia

For the avoidance of doubt, I've gone back to the start.

Rather than try to debug myself, I thought we could just go step by step.

I've git cloned the repository and subsequently installed gsnap anaconda muscle gsnap_db using -g 2016-11-07 and -a 2-4.2.0

FYI I had to --with-simd-level=sse42 when configuring gmap.

Also, I had to change the domain for anaconda to https://repo.continuum.io/archive/

config.sh : 

samtoolsexe=$samtools_HOME/bin/samtools
samtools_version=1
input_path=/scratch/et341/MT/MToolBox/MToolBox/MToolBox/in
output_name=/scratch/et341/MT/MToolBox/MToolBox/MToolBox/out
list=/scratch/et341/MT/MToolBox/MToolBox/MToolBox/in/bams.txt
input_type=bam
ref=RCRS
UseMarkDuplicates=true
UseIndelRealigner=true
MitoExtraction=true


With this set-up, I get the following error:

##### ERROR MESSAGE: Input files reads and reference have incompatible contigs: No overlapping contigs found.
##### ERROR   reads contigs = [chrRSRS]
##### ERROR   reference contigs = [chrRCRS]

even though the config comments state that the default is RCRS.

I noticed there was a setup.sh file with SRS-related variables set, so I changed those to CRS equivalents -

mtdb_fasta=chrRCRS.fa
hg19_fasta=hg19RCRS.fa
mtdb=chrRCRS
humandb=hg19RCRS

At this point it complains because:

File /scratch/et341/MT/MToolBox/MToolBox/genome_fasta/chrRCRS.fa does not exist. Indeed, the fa.gz files are one directory up from that one. 

I'd rather stop here and ask you for advice

thanks
Ernest
