### ISSUE TITLE
fastq.gz input not recognized 

### ISSUE THREAD

**Issue by Ros85** [mitoNGS/MToolBox#23]
When trying to launch MToolBox with a fastq.gz input file, and specifying this input type in the config.sh, the program returns an error saying "Input format not recognized".

**Comment by clody23** [comment]
Hi Rosanna,

`fastq.gz` file is not a supported argument of the pipeline, although it is able to read from gzipped files. 
You should still use `input_type=fastq` with fastq gzipped files. 

Best,
C
