### ISSUE TITLE
multiple annotation.csv files

### ISSUE THREAD

**Issue by ma-diroma** [mitoNGS/MToolBox#27]
The generation of multiple annotation.csv files for fragmented samples with lots of best predicted haplogroups causes issues in summary.txt generation.

**Comment by domenico-simone** [comment]
Which error is thrown? Can you post a seq file to reproduce it?

Il giorno mar 4 apr 2017 alle 12:25 Maria Angela Diroma <
notifications@github.com> ha scritto:

**Comment by ma-diroma** [comment]
Log:

No annotation.csv found. Exit

within the folder there are more than 4000 annotation.csv files.
prioritized_variants.txt and summary.txt were not generated.
Please find attached OUT2-sorted.bam file, generated by MToolBox map-exome
[OUT2-sorted.bam.zip](https://github.com/mitoNGS/MToolBox/files/892942/OUT2-sorted.bam.zip)

**Comment by biowizz** [comment]
Hello, I am facing the exact same issue. Did you resolve this issue?

**Comment by clody23** [comment]
This issue should be now solved. Please git pull the new changes to your local installation of MToolBox.

Best,
C
