### ISSUE TITLE
if [ -f OUT_*/*annotation.csv ] -> binary operator expected

### ISSUE THREAD

**Issue by 3i-v** [mitoNGS/MToolBox#28]
Dear,

Here is the description of the error:
`Parsing variant data for sample IonXpress_003...
Best haplogroup predictions for sample IonXpress_003 : ['V_150', 'V16']
Functional annotation for haplogroup V_150
Functional annotation for haplogroup V16
**Success.**

(...)/MToolBox-master_v1.0/MToolBox/MToolBox.sh: line 487: [: OUT_IonXpress_003/IonXpress_003.V16.annotation.csv: **binary operator expected**
**No annotation.csv found**. Exit`

Thank you very much for your help, and do not hesitate to ask if you need additional information.

----------
This error ocurred with 1 of my 19 samples I analysed. This sample is the only one on which 2 haplogroups have been identified.
The error seems to come from the lane 487 in MToolBox.sh, that is:
`if [ -f OUT_*/*annotation.csv ]`
Both of the annotation.csv files have been generated in the previous step, and contain results.

Above, here is the list of the files generated into the `OUT_IonXpress_003` folder:
`total 113664`
`  128 IonXpress_003.V16.annotation.csv`
`  128 IonXpress_003.V_150.annotation.csv`
`  128 IonXpress_003_merged_diff.csv`
`  128 IonXpress_003.sorted.csv`
`  256 IonXpress_003.csv`
`  128 IonXpress_003-coverage.txt`
`  128 IonXpress_003-contigs.fasta`
`  640 IonXpress_003-table.txt`
`10368 OUT2.pileup`
`  128 OUT2-sorted.bam.bai`
` 3840 OUT2-sorted.bam`
` 3840 OUT2.bam`
`11136 MarkTmp.tar.gz`
`14336 OUT2.sam`
`  128 OUT.realigned.bai`
`11392 OUT.realigned.bam`
`  128 OUT.sam.bam.bai`
`  128 tmp`
`14336 OUT.sam`
`15104 outhumanS.sam`
`  128 loghumanS.txt`
`11776 outmt.fastq`
`15104 outmt.sam`
`  128 logmt.txt`

**Comment by Pilibeibei** [comment]
I met the same issue: no annotation.csv found. Have you fixed it?

**Comment by clody23** [comment]
This issue should be now solved. Please git pull the new changes to your local repo.

best,
C

**Comment by 3i-v** [comment]
@clody23 Thank you very much for the update. The analysis works perfectly now with multi-haplogroups predictions.
-----------------------
Parsing variant data for sample IonXpress_003...
Best haplogroup predictions for sample IonXpress_003 : ['V_150', 'V16']
Functional annotation for haplogroup V_150
Functional annotation for haplogroup V16
Looking for prioritized variants...

Prioritization analysis done.

Analysis completed!
