### ISSUE TITLE
output file issue when input multiple files

### ISSUE THREAD

**Issue by Pilibeibei** [mitoNGS/MToolBox#33]
I have tested MToolBox.sh for one input file, that totally works fine. However, when I input 6 files as a list, it showed "MToolBox-master/MToolBox/MToolBox.sh: line 486: [: too many arguments
No annotation.csv found. Exit", I have got VCF_file, just no summary.txt and prioritized_variants.txt

When I run 10 files as a list, it shows 
##### GENERATING VCF OUTPUT...
Reference sequence used for VCF: RSRS
Traceback (most recent call last):
  File "/project/bondy/MToolBox-master/MToolBox/VCFoutput.py", line 32, in <module>
    VCFoutput(VCF_dict, reference=reference_sequence)
  File "/project/bondy/MToolBox-master/MToolBox/mtVariantCaller.py", line 1165, in VCFoutput
    i.INFO['AC'][index] += 1
IndexError: list index out of range

I am wondering whether MToolBox.sh has a limit for the number or the size of input files? I have several hundreds of files need to run, it's bit if I can only run 5 files at one time. 

Thanks

**Comment by jpt1016** [comment]
I ran in to this error before. I've forked this repo and made a fix in to the mtVariantCaller.py, assembleMTgenome.py among other changes.

**Comment by Pilibeibei** [comment]
That's wonderful! Do you mind sharing your the changes of mtVariantCaller.py and assembleMTgenome.py scripts that you used? Appreciate ahead

**Comment by jpt1016** [comment]
Just check my repositories and use the files from my fork

**Comment by Pilibeibei** [comment]
That's very helpful. I appreciate your help

**Comment by Pilibeibei** [comment]
Hi, jpt1016, I have tried to use the files from your fork, and use MToolboxLaunch.py to run the analysis as following
"python MToolboxLaunch.py -i /test/test_config.sh"
I got the error message:
Traceback (most recent call last):
 File "MToolboxLaunch.py", line 27, in <module>
 if os.path.isfile(config_file) and os.path.exists(input_path):
 File "/usr/lib/python2.7/genericpath.py", line 26, in exists os.stat(path)
 Would you please tell me more about how to use your script? I didn't find any readme file of your revised code. Should I still use "MToolBox.sh -i " or something else?
Appreciate ahead.

**Comment by jpt1016** [comment]
If you run that script as just:
"python MToolboxLaunch.py --help" 
It will display all of the options. You're missing the -p argument, also make sure to add a '/' to the end of your path, as i'm simply using a chdir command to look for files in that path. I realize this is redundant, as in the config file there is an option to set your path, I will eventually remove all the redundancies. 

I'm about to push a new change to my repo, adding two different filtering options to the final report. I will also better document the changes I have made. 

Thanks for bringing up these concerns!

**Comment by Pilibeibei** [comment]
Thanks for your quick reply. I looked at help file before I run it. I have
tried python MToolboxLaunch.py -i /test/test_config.sh -p /test/ -o /test/

Another error showed up:
Traceback (most recent call last):
File "MToolboxLaunch.py", line 32, in <module>
if os.path.isfile(VCF_file.vcf):
NameError: name 'VCF_file' is not defined

For the files have not called variants, I don't have vcf file to define.
Would you please help me to fix this?

Appreciate ahead.

**Comment by jpt1016** [comment]
By the time the interpreter reaches that line, it should have already run MToolBox.sh. So there should be a VCF_file.vcf that is generated by the original MToolbox pipeline.

**Comment by Pilibeibei** [comment]
I have tested many times, same error come out. I defined -p -i -o in MToolboxLaunch.py. Then I checked MToolBox.out file, it shows the error starts from mapExome.py
Traceback (most recent call last):
 File "/home/MToolBox-master/MToolBox/mapExome.py", line 66, in <module>
 if not os.path.exists(folder): os.mkdir(folder)
OSError: [Errno 71] Protocol error: '/media/OUT_F-00-79-1477'

Since I am running this on the Ubuntu in virtual machine, I though it may have some connection issue, so I cd to the path of the files I want to analysis then run it. It worked before to fix this problem in mapExome.py, but not for MToolboxLaunch.py.

Would you please tell me how to fix this?

Thanks

**Comment by jpt1016** [comment]
This script is very much a work in progress, currently I'm only getting results with fastq inputs from long-range PCR data. I'm working with WES data in the form of BAM files and working on a way to get the pipeline working. I'm close, but the scripts on my fork are now quite outdated; I've made many changes and improvements. Once it's working for my WES data I will push new changes, I don't see the point to commit changes that are solving small issues and not the bigger picture. 

I thought it was working, but clearly it is not.

**Comment by Pilibeibei** [comment]
Would you mind send me your email so we can talk about this more?

**Comment by clody23** [comment]
This error has been fixed as of 14 August 2017.
