### ISSUE TITLE
How or where I can get the file " MITOMAP_HMTDB_known_indels_chrRSRS.vcf"

### ISSUE THREAD

**Issue by PeggyHXY** [mitoNGS/MToolBox#35]
HI，
when I used the RSRS as reference,the error is as follow:
##### ERROR MESSAGE: Couldn't read file MToolBox-master/MToolBox/data/MITOMAP_HMTDB_known_indels_chrRSRS.vcf

Can you tell me how or where I can get the file " MITOMAP_HMTDB_known_indels_chrRSRS.vcf"?
Thank you very much!

**Comment by clody23** [comment]
Hi,

this file is downloaded together with all other files used by MToolBox when you do a git clone of the repository. 

You should find this file in the `/path/to/your/MToolbox_master/MToolBox/data/` of  your local copy of MToolBox. 

If the file is not there it may be that something went wrong when you git cloned the MToolBox repo.
Please, check that files you see in the MToolBox github repo are all in your local copy of the tool.

The original version of this file can be found here:
https://github.com/mitoNGS/MToolBox/blob/master/MToolBox/data/MITOMAP_HMTDB_known_indels_RSRS.vcf


Best,
C

**Comment by PeggyHXY** [comment]
$ ref_name=$(echo $mtdb_fasta | cut -f 1 -d .)
$ mtdb_fasta=chrRSRS.fa
$ echo $ref_name
chrRSRS
so,The only difference of" MITOMAP_HMTDB_known_indels_chrRSRS.vcf" and the file in your path MToolBox/data/  is the filename exists 'chr' or not.

**Comment by clody23** [comment]
Hi, 

sorry, but I don't understand what you mean here. Are you making a comparison between the `MITOMAP_HMTDB_known_indels_chrRSRS.vcf` file (which you find in the MToolBox/data folder)  and a previous file provided by the MToolBox pipeline or a file that you provide to the pipeline?

Best,
C
