### ISSUE TITLE
fa file doesnt exist

### ISSUE THREAD

**Issue by jeffgreen123** [mitoNGS/MToolBox#40]
I keep getting the following error whenever I try to run the HG00119 example 

sudo MToolBox.sh -i HG00119.conf > HG00119.log

File (...)/MToolBox-master/genome_fasta/chrM.fa does not exist.
Unable to compute haplogroup. Exit

While the folder genome_fasta has the file chrM.fa.gz, however that file is unable to be unzipped. Am I missing something or is there a bug? 

Thanks.

**Comment by PeggyHXY** [comment]
You maybe not build genomes database successfully.

**Comment by jeffgreen123** [comment]
Okay, I solved this, but now it keeps saying annotation.csv not found. Am I missing a file that I need?

**Comment by clody23** [comment]
Hi @jeffgreen123 

could you please copy-paste the full .log file here, to help us understanding the error?

thanks
C
