### ISSUE TITLE
can MToolBox use stock hg19

### ISSUE THREAD

**Issue by EricDeveaud** [mitoNGS/MToolBox#44]
Hello, 

I would like to know if MToolBox can use  hg19.fa from ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes 

our cluster host hg19.fa genome obtained by concatenating all chr#.fa.gz 
so our hg19.fa genome does not contain some data provided by the on hosted on https://sourceforge.net/projects/mtoolbox/files/genome_fasta/
eg no _random, no chrUn_* and so on.

we also have already available, hg19.fa.fai and gsnap indexes for this hg19 release.

can we use those data, or will it introduce some loose in the result accuracy ?
sorry if this looks like a dumb question, but I'm not biologist, just the guy in chargge of the installation of the programs ;-)

best regards

Eric

NB I was abble to run MToolBox with this data and also with the hg19RSRS you provided and over the >4K files generated on my tests 
I did not found any differences using hg19.fa vs hg19RSRS

**Comment by clody23** [comment]
Hi,

At the moment the  hg19 fasta used for the gmap db are hardcoded in the `install.sh` script but we plan to change this in next MToolBox releases, to allow more flexibility.

For now you could use your own gmap db installation based on UCSC hg19.fa as long as it contains the rCRS sequence (https://www.ncbi.nlm.nih.gov/nuccore/251831106) or RSRS (http://www.phylotree.org/resources/RSRS.fasta) as mitochondrial reference sequences, which are mandatory for MToolBox. Also please make sure that mitochondrial chromosome name is the same in the hg19.fa,  in the mitochondrial fasta reference and related gmap databases you use.

Also, you have to make sure to use the correct file names in the configuration file. 
Specifically, you should change the following arguments with the correct fasta and gmap db file names

```
#the mitochondrial reference fasta name
mtdb_fasta=

#the nuclear + mitochondrial reference fasta name
hg19_fasta=

#the gmap db built on the mitochondrial reference fasta
mtdb=

#the gmap db built on the nuclear+ mitochondrial reference fasta
humandb=
```

**Comment by clody23** [comment]
forgot to say that, if your gsnap installation, fasta files and gmap db are no in the MToolBox/bin directory,  you should also specify the full path to `gsnap executable`, `gmap db folder` and `genome_fasta folder` in the configuration file. 

```
gsnapexe=/full/path/to/gsnap
gsnapdb=/full/path/to/gsnap_db_folder/
genome_fasta=/full/path/to/genome_fasta_folder/
```
Best,
C

**Comment by EricDeveaud** [comment]
thanks for all this valuable information

Eric
