### ISSUE TITLE
mtVariantCaller issue (line 967) | IndexError: string index out of range

### ISSUE THREAD

**Issue by 3i-v** [mitoNGS/MToolBox#46]
@jich-MCTP, I open here a new issue in response of your comment in issue #38 
Thank you very much for your help,
----------------------

##### ASSEMBLING MT GENOMES WITH ASSEMBLEMTGENOME...

WARNING: values of tail < 5 are deprecated and will be replaced with 5

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
Traceback (most recent call last):
  File "(...)/MToolBox/**assembleMTgenome.py", line 443**, in <module>
    mut_events = mtvcf_main_analysis(mt_table, sam_file, sample_name, tail=tail)
  File "(...)/MToolBox/**mtVariantCaller.py", line 967**, in mtvcf_main_analysis
    deletions.append(mtDNAseq[delflank])
**IndexError: string index out of range**

##### GENERATING VCF OUTPUT...
Traceback (most recent call last):
  File "(...)/MToolBox/VCFoutput.py", line 33, in <module>
    VCF_dict = ast.literal_eval(open('VCF_dict_tmp', 'r').read())
IOError: [Errno 2] No such file or directory: 'VCF_dict_tmp'

**Comment by 3i-v** [comment]
Hi, do you have any update ? Thank you

**Comment by 3i-v** [comment]
I've run again MToolBox with the most recent version (commit 4ac8db7, 2017-10-23). The same error is obtained:

**Comment by clody23** [comment]
This issue should be now fixed with the latest changes. Please do git pull in your local installation of MToolBox and launch MToolBox again.
See github issue #64 for further details.

best,
Claudia
