### ISSUE TITLE
Unable to compute haplogroup. ExitParsing pathogenicity table...

### ISSUE THREAD

**Issue by itigupta24** [mitoNGS/MToolBox#47]
When running MToolBox on the example dataset (sim_data) provided, i met with the following error:
**

I##### ASSEMBLING MT GENOMES WITH ASSEMBLEMTGENOME...

WARNING: values of tail < 5 are deprecated and will be replaced with 5

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000

##### GENERATING VCF OUTPUT...
Reference sequence used for VCF: RCRS

##### PREDICTING HAPLOGROUPS AND ANNOTATING/PRIORITIZING VARIANTS...

Haplogroup predictions based on RSRS Phylotree build 17
Your best results file is  mt_classification_best_results.csv

Loading contig sequences from file simulation100X-contigs.fasta
Loaded 1 contig sequences

Aligning Contigs to mtDNA reference genome...

Sequence haplogroup assignment

Classification according to tree: /home/iti.gupta/archive/MToolBox/MToolBox/data/phylotree_r17.pickle
genome_state is  incomplete
OrderedDict()
====================
------------------------------
Contig alignment to MHCS and rCRS
Unable to compute haplogroup. ExitParsing pathogenicity table...
Parsing variability data...
Parsing info about haplogroup-defining sites...
Parsing info about haplogroup assignments...
No annotation.csv found. Exit

**

**Comment by clody23** [comment]
Please see issue #77
