### ISSUE TITLE
Unable to get .vcf file after finish running MToolBox

### ISSUE THREAD

**Issue by tanlingqiao** [mitoNGS/MToolBox#50]
Hi, good day! 
I used MToolbox to run on .fastq file of RNA sequencing data, the whole process ran smoothly and I got the output files. However, I cannot get .vcf file which I need to do subsequent analysis. I got "VCF_dict_tmp" file but can't get VCF_file.

Appreciate if any helps given, thanks!

**Comment by clody23** [comment]
Hi, 

the MToolBox pipeline does not support RNA sequencing data at the moment, but is meant to work on human mitochondrial DNA only (it uses default GSNAP settings for DNA-alignment only, that the user cannot change at the moment), so it is hard to give you support on this issue.

Although we definitely discourage the use of MToolBox for other purposes that are not the mtDNA analysis, in principle the pipeline should be able to run from any fastq file up to the VCF file generation, haplogroup prediction and mitochondrial annotation. 

We would need a log file with the error generated to be able to help you.
Best,
Claudia

we are sorry, but we are planning to release
