### ISSUE TITLE
can MToolBox handle pure mtDNA sequencing data?

### ISSUE THREAD

**Issue by MatthewP-Newbee** [mitoNGS/MToolBox#57]
Hi,
My data may come from mtDNA sequencing after multi-PCR, which means its not drived from WES or WGS. I want to know how can I analyse such data by using MToolBox.
Thanks

**Comment by clody23** [comment]
Hi,

apologies for the very late reply. 

MToolBox can handle also sequencing targeted on mtDNA, as long as the input is fastq(gz)/sam/bam.

Best wishes,
Claudia
