### ISSUE TITLE
DP4 in the VCF File (enhancement) ?

### ISSUE THREAD

**Issue by 3i-v** [mitoNGS/MToolBox#61]
Is it possible to add the strand bias (DP4) into the VCF info field ?
Thank you,
v.

**Comment by clody23** [comment]
Hi, 

yes, this is indeed an improvement we are planning to do in the next version of the tool we are currently working on. 

Best regards,
Claudia

**Comment by clody23** [comment]
We have released version 1.2 version of MToolBox that supports the calculation of the read depth per strand of the ALT allele only. This is now reported as an additional field in the VCF (SDP).
