### ISSUE TITLE
why is there no HF information  and reference sequence for the prioritized variants file??

### ISSUE THREAD

**Issue by Confurious** [mitoNGS/MToolBox#66]
As the final output file, I would expect it to contain ref allele as well as HF which are included in the VCF and/or annotation.csv file. I consider them to be essential in pooling the results together for big cohort studies. Would it be possible to add these two columns to the prioritized_variants.txt ?

Thanks!

**Comment by clody23** [comment]
Hi,

We are planning a MToolBox code refactoring where the prioritization file will likely disappear, in favour of fewer and clearer outputs.  
I am afraid this is not going to be a further enhancement that we plan to do with future updates of the tool. 

best,
C
