### ISSUE TITLE
Select the MAF

### ISSUE THREAD

**Issue by ndierckx** [mitoNGS/MToolBox#76]
Hi,

Is it possible to only detect heteroplasmic variants above a certain value (> 1% for example)
Else it generates many false positives with very low frequencies?

Greets

**Comment by domenico-simone** [comment]
Hi,

at the moment this is not implemented in the tool, but it could be a possible improvement, although I think that having a "raw" VCF with all the detected variants (to be eventually filtered downstream) is the best option.

Thanks,

Domenico

**Comment by ndierckx** [comment]
Hi,

You mean frequencies below 1 %? Actually I go till 0.7%, but lower has no point I think because then it is impossible to detect with a decent accuracy, at least not with Illumina data.. But I still have to upload the NOVOPlasty version with the final heteroplasmy detection module

**Comment by clody23** [comment]
Hi,

MToolBox does not have any hard cutoff for heteroplasmy. 1% heteroplasmy is an arbitrary threshold as much as any other heteroplasmy cutoff one could choose. We prefer instead to leave the heteroplasmy threshold choice to the user, given that, to our experience, cutoffs depend on the read depth and the quality of the sequencing.

However, we will consider your suggestion for the next release of MToolBox.

We're not sure we understand what you mean with your statement about Novoplasty. Anyway, we are happy to compare MToolBox results with the ones from Novoplasty.

Best regards,

Claudia & Domenico

**Comment by ndierckx** [comment]
Hi,

With NOVOPlasty you can choose your threshold too, it's the 'heteroplasmy' option int he config file. But the limit I advice is 0.7% and I never use lower.. It would be nice if you can choose the MAF before running MToolBox, because now you have to filter the low percentages out.

Greets,

Nicolas

**Comment by domenico-simone** [comment]
Hi,

in the aux folder the repo there is a script `filter_HF.py` that performs the downstream filtering of the variants based on HF and DP. In the meantime, we don't think a change in the variant reporting will be our priority in the near future.

Regards,

Domenico
