### ISSUE TITLE
'None' genotypes

### ISSUE THREAD

**Issue by cefrnch** [mitoNGS/MToolBox#84]
Hi,

With the newest version v1.2, some (but not all) multi-allelic sites in sample.vcf have have 'None' as the genotype as below: 

chrMT   310     .       T       TC,C    .       PASS    AC=1,1;AN=2     GT:DP:HF:CILOW:CIUP:SDP None:1492:1.0,0.193:0.997,0.169:1.0,0.22:36;1456,95;88

Position 310 has this problem in most of my samples, but it sometimes happens at other positions. Below is the beginning of a sample.vcf showing the issue. I'm currently getting around it by replacing 'None' with '.'

Thank you.

##fileformat=VCFv4.0
##reference=chrRCRS
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Reads covering the REF position">
##FORMAT=<ID=HF,Number=.,Type=Float,Description="Heteroplasmy Frequency of variant allele">
##FORMAT=<ID=CILOW,Number=.,Type=Float,Description="Value defining the lower limit of the confidence interval of the heteroplasmy fraction">
##FORMAT=<ID=CIUP,Number=.,Type=Float,Description="Value defining the upper limit of the confidence interval of the heteroplasmy fraction">
##FORMAT=<ID=SDP,Number=.,Type=String,Description="Strand-specific read depth of the ALT allele">
##INFO=<ID=AC,Number=1,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NGC00378_01_mito
chrMT   263     .       A       G       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2596:0.999:0.997:1.0:973;1621
chrMT   299     .       C       CA      .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2246:0.005:0.003:0.009:11;0
chrMT   302     .       A       AC,C    .       PASS    AC=1,1;AN=3     GT:DP:HF:CILOW:CIUP:SDP 0/1/2:829:0.101,0.017:0.083,0.01:0.124,0.028:72;12,1;13
chrMT   309     .       C       CCT     .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1715:0.003:0.001:0.008:0;6
chrMT   310     .       T       TC,C    .       PASS    AC=1,1;AN=2     GT:DP:HF:CILOW:CIUP:SDP None:1492:1.0,0.193:0.997,0.169:1.0,0.22:36;1456,95;88
chrMT   316     .       G       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1841:0.009:0.005:0.014:16;0
chrMT   318     .       T       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1784:0.003:0.001:0.008:6;0
chrMT   326     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1990:0.003:0.001:0.006:5;0
chrMT   333     .       T       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2068:0.004:0.002:0.008:8;0
chrMT   357     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2271:0.002:0.001:0.005:5;0
chrMT   366     .       G       A       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2251:0.002:0.001:0.005:5;0
chrMT   432     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1639:0.004:0.001:0.008:2;4
chrMT   435     .       C       A       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2413:0.002:0.001:0.005:5;0
chrMT   439     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1617:0.015:0.01:0.022:23;1
chrMT   441     .       C       A       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2221:0.002:0.001:0.005:5;0
chrMT   442     .       T       A,C     .       PASS    AC=1,1;AN=3     GT:DP:HF:CILOW:CIUP:SDP 0/1/2:1671:0.003,0.004:0.001,0.002:0.007,0.009:5;0,7;0
chrMT   444     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1983:0.003:0.001:0.007:3;3
chrMT   446     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1850:0.003:0.001:0.007:6;0
chrMT   448     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1944:0.003:0.001:0.007:5;1
chrMT   451     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1888:0.003:0.001:0.006:3;2
chrMT   456     .       C       T       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2242:0.002:0.001:0.005:5;0
chrMT   464     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1135:0.032:0.023:0.044:32;4
chrMT   466     .       T       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1554:0.003:0.001:0.008:5;0
chrMT   470     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1895:0.015:0.01:0.021:28;0
chrMT   471     .       T       G       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1800:0.003:0.001:0.007:0;5
chrMT   478     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1894:0.003:0.001:0.006:5;0
chrMT   484     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2063:0.004:0.002:0.008:8;0
chrMT   485     .       T       G       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2020:0.002:0.001:0.006:0;5
chrMT   499     .       G       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2043:0.03:0.023:0.038:60;1
chrMT   503     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1724:0.012:0.008:0.019:21;0
chrMT   508     .       A       C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1640:0.004:0.002:0.009:6;1
chrMT   511     .       CAG     C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1953:0.012:0.008:0.018:15;9
chrMT   512     .       AGC     A,CGC   .       PASS    AC=1,1;AN=3     GT:DP:HF:CILOW:CIUP:SDP 0/1/2:1856:0.008,0.005:0.004,0.002:0.013,0.009:5;9,9;0
chrMT   513     .       GCA     G,CCA   .       PASS    AC=1,1;AN=2     GT:DP:HF:CILOW:CIUP:SDP None:2346:1.0,0.003:0.998,0.001:1.0,0.007:1154;1192,6;0
chrMT   515     .       A       G       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:175:0.114:0.075:0.171:8;12
chrMT   518     .       CA      C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:2095:0.004:0.002:0.008:6;3
chrMT   520     .       CA      C       .       PASS    AC=1;AN=2       GT:DP:HF:CILOW:CIUP:SDP 0/1:1998:0.003:0.001:0.007:5;1

**Comment by clody23** [comment]
Hi,

this issue should have been resolved by this latest fix:
https://github.com/mitoNGS/MToolBox/commit/890ed0998a2440a3aedeb97d3c6461a633674c2a

Can you please update and rerun and let us know if this resolves your issue?

Many thanks.

Claudia

**Comment by cefrnch** [comment]
Hi Claudia,
Yes, this fixed it. Thanks very much!
Courtney

**Comment by clody23** [comment]
Great!

Best wishes,
Claudia
