### ISSUE TITLE
./MToolBox.sh: line 346: java: command not found

### ISSUE THREAD

**Issue by smukh18** [mitoNGS/MToolBox#88]
MToolbox starts running and then gives the following error
Outfile saved on /home/smukherjee/Documents/idp/Output/OUT_R6535_C284PACXX_TCCGGAGA_L005_R1_001/OUT.sam.
Done.

SAM files post-processing...

##### SORTING OUT.sam FILES WITH PICARDTOOLS...

./MToolBox.sh: line 346: java: command not found
Success.

[E::hts_open_format] fail to open file 'OUT.sam.bam'
samtools index: failed to open "OUT.sam.bam": No such file or directory
Skip Indel Realigner...
cat: OUT.sam.bam: No such file or directory

Please help

**Comment by clody23** [comment]
Hi,

you should have java installed to run some of the MToolBox dependancies. Please, make sure you have that installed before running MToolBox.

Best wishes,

Claudia

**Comment by EricDeveaud** [comment]
sorry I did not think it was so difficult to add few lines to check that java is availble 

maybe you would like to copy paste the following.

```
JAVA=`command -v java`

if [ -z ${JAVA} ]; then
  echo "You need java to run MToolBox"
  exit 1
fi
```

where  ? is up to you. 
I would personaly set it just after getopt section. 

best regards

Eric
